### ISSUE TITLE
Documentation for React Cosmos for Vite

### ISSUE THREAD

**Issue by tsanyqudsi** [react-cosmos/rfcs#24]
Hi,

I know React Cosmos isn't ready for Vite except for doing workaround. I found a nice repo from kazuma1989 ( https://github.com/kazuma1989/react-cosmos-with-vite ) and i think you guys should put it inside official docs for now.

**Comment by ovidiuch** [comment]
Cosmos now have first class support for Vite: https://github.com/react-cosmos/react-cosmos/blob/main/docs/README.md#getting-started 🥳
