### ISSUE TITLE
Toggle dark mode

### ISSUE THREAD

**Issue by orbachar** [react-cosmos/rfcs#26]
is it possible to add a dark mode toggle? 
all I need is to toggle a class name on html tag, but couldn’t figure a way of doing so.

**Comment by ovidiuch** [comment]
This is very vague. But you can combine [Decorators](https://github.com/react-cosmos/react-cosmos/blob/main/docs/README.md#decorators) with [Control panel hooks](https://github.com/react-cosmos/react-cosmos/blob/main/docs/README.md#control-panel) to achieve something like that.

**Comment by orbachar** [comment]
Thanks will try
