### ISSUE TITLE
Bun.sh support

### ISSUE THREAD

**Issue by noahehall** [react-cosmos/rfcs#27]
React Cosmos is one of the few component libraries that could ideally be paired with Bun.sh
- no requirement for react prop-types, webpack, vite, etc
- custom *bun*dler integration (perfect!)

However,  it currently throws when using bun to bundle cosmos fixtures.

E.g. this [repo with a div as a fixture](https://github.com/noahehall/react-ideal-image/blob/react-cosmos-isbuffer-not-a-function/src/ima.fixture.tsx)

will throw an error about ` isBuffer3.default is not a function`
![image](https://github.com/react-cosmos/rfcs/assets/10324554/e8a33615-b64e-4d22-80c0-e04dd7c3f5e2)

Potentially due to Bun's [incomplete nodejs Buffer api](https://bun.sh/docs/runtime/nodejs-apis#globals)

I figure there are two routes we can take
- Wait on `Bun.sh` to complete their buffer api
- Provide a more resilient implementation in cosmos

**Comment by ovidiuch** [comment]
The error seems to come from the `isEqual` Lodash method. Maybe this is fixed in the latest Bun versions? https://github.com/oven-sh/bun/issues/936

**Comment by noahehall** [comment]
@skidding interesting - honestly i didnt dive deep and correlated the buffer error msg to the incomplete buffer api - victim of a very long day. 

but confirmed - lol simply clicking on the error was enoug ;)
![image](https://github.com/react-cosmos/rfcs/assets/10324554/bb77f41c-7eb4-485f-9bc3-95dcc0617736)


will update the devs over at bun.sh
